export const DATA_SOURCE = 'DATA_SOURCE'; 
export const USER_REPOSITORY = 'USER_REPOSITORY'; 
export const TOPIC_REPOSITORY = 'TOPIC_REPOSITORY';
export const PHRASE_REPOSITORY = 'PHRASE_REPOSITORY';
export const RECORDING_REPOSITORY = 'RECORDING_REPOSITORY';
export const USER_PROGRESS_REPOSITORY = 'USER_PROGRESS_REPOSITORY';
